### ISSUE TITLE
respect pyproject.toml's tool.doq

### ISSUE THREAD

**Issue by Freed-Wu** [yaegassy/coc-pydocstring#16]
`pyproject.toml`:

```
[tool.doq]
template_path = "templates"
```

```shell
$ tree templates
 templates
├──  class.txt
├──  def.txt
└──  noarg.txt
```

However, edit `src/XXX/XX.py` and use `Add docstring for "File" by pydocstring` will not use templates.

**Comment by yaegassy** [comment]
I have been able to reproduce this issue. It seems that in the current implementation of coc-pydocstring, it is necessary to set the `template_path` in pyproject.toml with the "absolute" path.

```toml
[tool.doq]
template_path = "/ABSOLUTE/PATH/TO/templates"
```

It seems that the essential adjustment requires adding functionality to coc-pydocstring itself. Since it may involve a slightly complex solution, I will find some time to consider and address it.

**Comment by yaegassy** [comment]
Added functionality so that the `template_path` setting in `pyproject.toml` and `setup.cfg` will work even if the path is relative. Please update `coc-pydocstring`.
